site_name: CS Ref
site_url: https://csref.dev
site_description: A concise computer science reference with diagrams, notes, and worked examples.
site_author: CS Ref
repo_url: https://github.com/jaysalw>/csref.dev
repo_name: jaysalw/csref.dev
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  logo: images/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: teal
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Architecture:
      - Computer Architectures (Extended): computer-architectures-extended.md
  - About: about.md

plugins:
  - search
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - sitemaps:
      url: https://csref.dev
  - redirects:
      redirect_maps:
        old/architectures.md: computer-architectures-extended.md
  - mermaid2  

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:   
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-org>/csref.dev
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:  
  - docs
  - overrides
  - stylesheets

docs_dir: docs

use_directory_urls: true

strict: true

copyright: "See the License within the GitHub Repo for more details."
