site_name: CS Ref
site_url: https://csref.dev
site_description: A concise computer science reference with diagrams, notes, and worked examples.
site_author: CS Ref
repo_url: https://github.com/jaysalw/csref.dev
repo_name: jaysalw/csref.dev
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  logo: images/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: teal
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Level 3:
      - Overview: level-3/overview.md
      - Basic Programming:
          - Overview: level-3/basic-programming/overview.md
      - Core Topics:
          - Overview: level-3/core-topics/overview.md
      - Using Git:
          - Overview: level-3/using-git/overview.md
  - Level 4:
      - Overview: level-4/overview.md
      - Computing Skills:
          - Overview: level-4/computing-skills/overview.md
          - Computer Systems and Architecture: level-4/computing-skills/computer-systems-and-architecture.md
          - Data Representation: level-4/computing-skills/data-representation.md
          - Computational Thinking: level-4/computing-skills/computational-thinking.md
          - Python Fundamentals: level-4/computing-skills/python-fundamentals.md
          - Modelling and Abstraction: level-4/computing-skills/modelling-and-abstraction.md
          - Ethics and AI: level-4/computing-skills/ethics-and-ai.md
      - Software Development:
          - Overview: level-4/software-development/overview.md
      - Tech Stack:
          - Overview: level-4/tech-stack/overview.md
      - User Experience:
          - Overview: level-4/user-experience/overview.md

plugins:
  - search
  - bibtex:
      bib_file: docs/references.bib
      cite_style: ieee
      cited_only: true
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - redirects:
      redirect_maps:
        old/architectures.md: computer-architectures-extended.md
  - mermaid2

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaysalw/csref.dev
  generator: false

# Remove extra_css line because docs/stylesheets/extra.css is not in repo yet.
# extra_css:
#   - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Only watch the docs folder (exists). Remove non-existent paths.
watch:
  - docs

docs_dir: docs
use_directory_urls: true
strict: true

copyright: "See the License within the GitHub Repo for more details."
