site_name: csref.dev
site_url: https://csref.dev
repo_url: https://github.com/jaysalw/csref.dev
repo_name: jaysalw/csref.dev
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    # header tabs + grouped sidebar like your screenshot
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    # QoL
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - scheme: slate           # dark
      primary: green          # Material green
      accent: lime            # accent green
# terminal-green overrides (neon vibe)
extra_css:
  - assets/custom.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true

markdown_extensions:
  # core
  - admonition                # !!! note / tip / warning …
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  # Material/pymdown goodies
  - pymdownx.details          # collapsible admonitions
  - pymdownx.superfences      # fenced code & nesting
  - pymdownx.tabbed:
      alternate_style: true   # content tabs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Top-level groups here become HEADER TABS
# Headings inside become LEFT SIDEBAR "categories"
nav:
  - Home: index.md

  - Getting started:
    - Installation: getting-started/installation.md
    - Creating your site: getting-started/creating.md
    - Publishing your site: getting-started/publishing.md
    - Customization: getting-started/customization.md
    - Conventions: getting-started/conventions.md
    - Browser support: getting-started/browser.md
    - Philosophy: getting-started/philosophy.md
    - Alternatives: getting-started/alternatives.md
    - License: getting-started/license.md

  - Tutorials:
    - Blogs: tutorials/blogs.md
    - Social cards: tutorials/social-cards.md

  - Changelog:
    - How to upgrade: changelog/upgrade.md
