site_name: csref.dev
site_url: https://csref.dev
site_description: A concise computer science reference with diagrams, notes, and worked examples.
site_author: jaysalw
repo_url: https://github.com/jaysalw/csref.dev
repo_name: jaysalw/csref.dev
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  favicon: assets/logo.png
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      # follow user's browser/OS preference for light/dark by default
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: material/weather-night
        name: Switch theme
    - scheme: slate
      primary: indigo
      accent: teal
      media: '(prefers-color-scheme: dark)'
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Contributing: contributing.md
  - Level 3:
    - Overview: level-3/overview.md
    - Basic Programming:
      - Overview: level-3/basic-programming/overview.md
      - Learning objectives: level-3/basic-programming/learning-objectives.md
      - Variables & types: level-3/basic-programming/variables-and-types.md
      - Control flow: level-3/basic-programming/control-flow.md
      - Data structures: level-3/basic-programming/data-structures.md
      - Functions: level-3/basic-programming/functions.md
      - I/O & Debugging: level-3/basic-programming/io-and-debugging.md
      - Examples: level-3/basic-programming/examples.md
      - Exercises: level-3/basic-programming/exercises.md
      - Solutions: level-3/basic-programming/solutions.md
    - Core Topics:
      - Overview: level-3/core-topics/overview.md
      - AI:
        - Overview: level-3/core-topics/ai.md
        - ML fundamentals: level-3/core-topics/ai-ml-fundamentals.md
        - Deep learning: level-3/core-topics/ai-deep-learning.md
        - Ethics & fairness: level-3/core-topics/ai-ethics-fairness.md
      - Blockchain:
        - Overview: level-3/core-topics/blockchain.md
        - Smart contracts: level-3/core-topics/blockchain-smart-contracts.md
        - Privacy & scaling: level-3/core-topics/blockchain-privacy-scaling.md
      - Emerging technologies:
        - Overview: level-3/core-topics/emerging-technologies.md
        - Edge & cloud: level-3/core-topics/emerging-edge-cloud.md
        - IoT: level-3/core-topics/emerging-iot.md
        - Quantum: level-3/core-topics/emerging-quantum.md
      - Security & privacy: level-3/core-topics/security-and-privacy.md
      - Labs:
        - AI/ML Lab: level-3/core-topics/labs/ai-ml-lab.md
        - Blockchain Lab: level-3/core-topics/labs/blockchain-lab.md
        - Labs README: level-3/core-topics/labs/README.md
    - Using Git:
      - Overview: level-3/using-git/overview.md
      - Guide: level-3/using-git/guide.md
      - Examples: level-3/using-git/examples.md
      - Exercises: level-3/using-git/exercises.md
      - Using Git in VS Code: level-3/using-git/using-vs-code.md
  - Level 4:
      - Overview: level-4/overview.md
      - Computing Skills:
          - Overview: level-4/computing-skills/overview.md
          - Computer Systems and Architecture: level-4/computing-skills/computer-systems-and-architecture.md
          - Data Representation: level-4/computing-skills/data-representation.md
          - Computational Thinking: level-4/computing-skills/computational-thinking.md
          - Modelling and Abstraction: level-4/computing-skills/modelling-and-abstraction.md
          - Ethics and AI: level-4/computing-skills/ethics-and-ai.md
      - Software Development:
          - Overview: level-4/software-development/overview.md
      - Tech Stack:
          - Overview: level-4/tech-stack/overview.md
      - User Experience:
          - Overview: level-4/user-experience/overview.md

plugins:
  - search
  - bibtex:
      bib_file: docs/references.bib
      cite_style: ieee
      cited_only: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - redirects:
      redirect_maps:
        old/architectures.md: computer-architectures-extended.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaysalw/csref.dev
  generator: false

extra_css:
   - assets/custom.css

extra_javascript:
  - assets/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/mathjax-init.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/mermaid-init.js
  - assets/material-init.js
  - assets/prefers-color-scheme.js

watch:
  - docs

docs_dir: docs
use_directory_urls: true
strict: false

copyright: "See the License within the GitHub Repo for more details."
