site_name: csref.dev
site_url: https://csref.dev
repo_url: https://github.com/jaysalw/csref.dev
repo_name: jaysalw/csref.dev
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.footer
    - navigation.footer
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/custom.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-committers:
      repository: jaysalw/csref.dev
      branch: main
      enabled: true

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Level 3:
    - Overview: level-3/overview/
    - Basic Programming: level-3/basic-programming/
    - Core Topics: level-3/core-topics/
    - Using Git: level-3/using-git/
  - Level 4:
    - Overview: level-4/overview/
    - Computing Skills: level-4/computing-skills/
    - Software Development: level-4/software-development/
    - Tech Stack: level-4/tech-stack/
    - User Experience: level-4/user-experience/
