/**
 * Custom sidebars configuration to create per-module sidebars.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // keep a default autogenerated sidebar for other docs
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Level 3 overview (grouped)
  level3Sidebar: [
    {
      type: 'category',
      label: 'Level 3',
      items: [
        {
          type: 'category',
          label: 'CS301 - Example Module',
          items: [{type: 'autogenerated', dirName: 'level-3/cs301'}],
        },
        {
          type: 'category',
          label: 'CS302 - Another Module',
          items: [{type: 'autogenerated', dirName: 'level-3/cs302'}],
        },
      ],
    },
  ],

  // Per-module sidebars — these are used so the left sidebar can show only a module's pages
  'level-3-cs301-sidebar': [{type: 'autogenerated', dirName: 'level-3/cs301'}],
  'level-3-cs302-sidebar': [{type: 'autogenerated', dirName: 'level-3/cs302'}],

  // Level 4 overview (grouped)
  level4Sidebar: [
    {
      type: 'category',
      label: 'Level 4',
      items: [
        {
          type: 'category',
          label: 'CS401 - Capstone',
          items: [{type: 'autogenerated', dirName: 'level-4/cs401'}],
        },
      ],
    },
  ],

  'level-4-cs401-sidebar': [{type: 'autogenerated', dirName: 'level-4/cs401'}],
};

module.exports = sidebars;
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
