/**
 * Custom sidebars configuration to create per-module sidebars.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // (no global autogenerated tutorial sidebar — tutorial items removed)

  // Level 3 overview (grouped)
  level3Sidebar: [
    {
      type: 'category',
      label: 'Level 3',
      items: [
        {
          type: 'category',
          label: 'CS301 - Example Module',
          items: [{type: 'autogenerated', dirName: 'level-3/cs301'}],
        },
        {
          type: 'category',
          label: 'CS302 - Another Module',
          items: [{type: 'autogenerated', dirName: 'level-3/cs302'}],
        },
      ],
    },
  ],

  // Per-module sidebars — these are used so the left sidebar can show only a module's pages
  'level-3-cs301-sidebar': [{type: 'autogenerated', dirName: 'level-3/cs301'}],
  'level-3-cs302-sidebar': [{type: 'autogenerated', dirName: 'level-3/cs302'}],

  // Level 4 overview (grouped)
  level4Sidebar: [
    {
      type: 'category',
      label: 'Level 4',
      items: [
        {
          type: 'category',
          label: 'CS401 - Capstone',
          items: [{type: 'autogenerated', dirName: 'level-4/cs401'}],
        },
      ],
    },
  ],

  'level-4-cs401-sidebar': [{type: 'autogenerated', dirName: 'level-4/cs401'}],
};

module.exports = sidebars;
